// Code generated by "stringer -type=Structure"; DO NOT EDIT.

package lifting

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BastionRemnant-0]
	_ = x[DesertPyramid-1]
	_ = x[Igloo-2]
	_ = x[JungleTemple-3]
	_ = x[OceanRuin-4]
	_ = x[PillagerOutpost-5]
	_ = x[RuinedPortalOverworld-6]
	_ = x[RuinedPortalNether-7]
	_ = x[Shipwreck-8]
	_ = x[SwampHut-9]
	_ = x[Village-10]
}

const _Structure_name = "BastionRemnantDesertPyramidIglooJungleTempleOceanRuinPillagerOutpostRuinedPortalOverworldRuinedPortalNetherShipwreckSwampHutVillage"

var _Structure_index = [...]uint8{0, 14, 27, 32, 44, 53, 68, 89, 107, 116, 124, 131}

func (i Structure) String() string {
	if i < 0 || i >= Structure(len(_Structure_index)-1) {
		return "Structure(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Structure_name[_Structure_index[i]:_Structure_index[i+1]]
}
